Reworking the `propagate` interface for custom gates
MSRudolph/PauliPropagation.jl pull request #35
Opened 2024-12-10 10:47 UTC by MSRudolph

To preserve the idea of "the more you code, the higher performance everything will be", the generics for `applygatetoall!()` and `applygatetoone!()`. Needed to be reworked. Before, `applygatetoone!()` could not reasonably be overloaded without also overloading `applygatetoall!()`.

This new way is slightly less performant if one only overloads `apply()`, but it is much cleaner. I also believe that we could do a lower-level `delete!` on the dicts to minimize the performance hit down to basically nothing.

2024-12-11 07:55 UTC, teng10 requested changes
Thanks for the refactoring. It's looking better every time :)

Before you merge this PR, let's touch base soon

2024-12-11 07:55 UTC, teng10 commented on src/Propagation/generics.jl
> -        psum, second_psum, param_idx = mergingapply!(gate, psum, second_psum, thetas, param_idx; kwargs...)
Is it true that a Schrodinger picture of the evolution can be done by specifying `reverse == False`?

2024-12-11 07:55 UTC, teng10 commented on src/Propagation/generics.jl
> -        psum, second_psum, param_idx = mergingapply!(gate, psum, second_psum, thetas, param_idx; kwargs...)
Oh you also need to dagger each gate..

2024-12-11 07:55 UTC, teng10 commented on src/Propagation/specializations.jl
> +    empty!(psum)
I agree `aux_psum` is more descriptive, especially if we explain what it's used for. 

Would do a search through all files to replace it everywhere.

2024-12-11 07:55 UTC, teng10 commented on src/Propagation/generics.jl
So now `aux_psum` is always cleared, we are still returning it. Because it's better than deleting it and creating an empty `aux_psum` on the fly?

2024-12-11 08:56 UTC, MSRudolph commented on src/Propagation/generics.jl
> -        psum, second_psum, param_idx = mergingapply!(gate, psum, second_psum, thetas, param_idx; kwargs...)
Yes, we currently only support Heisenberg picture propagation, with Schrödinger picture being a clear next step. But this needs to be designed a bit more carefully.

2024-12-11 09:00 UTC, MSRudolph commented on src/Propagation/generics.jl
It is returned because they may get swapped. Added this here a26482b7953df4f5212954abd341a0ebd203528a.

2024-12-11 09:01 UTC, MSRudolph commented on src/Propagation/specializations.jl
> +    empty!(psum)
Done 472e037b7083d31827ee816dfbd0e21c64f0d7c0.

2024-12-12 18:38 UTC, TysonRayJones commented on src/PauliAlgebra/datatypes.jl
> +        if getnumcoeff(new_coeff) == 0
misleading name as discussed - could be better as `tonumber()` which makes it more intuitive that:
- when it receives a wrapper object, it returns the associated number
- when it receives a number, it returns itself

2024-12-12 18:46 UTC, TysonRayJones commented on src/PauliAlgebra/datatypes.jl
> +function +(pstr1::PauliString{TermType,CoeffType}, pstr2::PauliString{TermType,CoeffType}) where {TermType,CoeffType}
parameters `TermType` and `CoeffType` are nice and explicit, but make the signatures quite verbose. Consider keeping the full type name in the doc-strings (which is nice and clear), but abbreviate it in the code into a single-letter upper-case variable (maybe `T` for type). This is the common C++ convention although I cannot find it in the Julia style-guide; ChatGPT (potentially hallucinating) claims it is similar in Julia.

So consider:
```julia
"""
    +(pstr1::PauliString{TermType,CoeffType}, pstr2::PauliString{TermType,CoeffType})
Addition of two `PauliString`s. Returns a PauliSum.
"""
function +(pstr1::PauliString{TT,CT}, pstr2::PauliString{TT,CT}) where {TT,CT}
```
Inessential but could shrink a lot of boilerplate. It would be an inexcusable change if these templates only appeared once. But given they occur _a lot_, it might be worthwhile - but I'm not 100%. Food for thought!

2024-12-12 20:45 UTC, TysonRayJones commented on src/PauliAlgebra/datatypes.jl
> +The type of the Pauli string needs to be the keytype of the dictionary, and the coefficient `coeff` needs to be the keytype.
typo here; the final word should be `valuetype`. But I think it's also worth making explicit that `keytype=TermType` and `valuetype=CoeffType`

2024-12-12 20:46 UTC, TysonRayJones commented on src/PauliAlgebra/datatypes.jl
> +The type of the Pauli string needs to be the keytype of the dictionary, and the coefficient `coeff` needs to be the keytype.
typo here (same as previous comment). The final word should be `valuetype`. But I think it's also worth making explicit that `keytype=TermType` and `valuetype=CoeffType`

2024-12-12 20:46 UTC, TysonRayJones commented on src/PauliAlgebra/datatypes.jl
> +The type of the Pauli string needs to be the keytype of the dictionary, and the coefficient `coeff` needs to be the keytype.
as per previous comment

2024-12-12 20:47 UTC, TysonRayJones commented on src/PauliAlgebra/datatypes.jl
> +    # delete if the coefficient would be set to 0
this comment is incorrect here; this function unconditionally deletes

2024-12-12 20:47 UTC, TysonRayJones commented on src/PauliAlgebra/datatypes.jl
> +Empty the `PauliSum` by emtpying the dictionary on the `terms` fields.
typo in "emptying" (as "emtpying")

2024-12-12 20:51 UTC, TysonRayJones commented on src/Propagation/generics.jl
>  Propagate a `PauliSum` through the circuit `circ` in the Heisenberg picture.
It is absolutely crucial to clarify in the doc that...
- the dagger of each element in `circ` is ultimately applied (in conjugation) upon `psum`, as per the Heisenberg picture
-  whether `thetas` should be the "Schrodinger picture params", or have been pre-conjugated by the user (i.e. negated for rotations)

Consider something like
"This means the PTM of the conjugate-transpose of each operator in the reverse order of circuit is applied in-turn upon `psum`. The list `thetas` should be those such that..."

2024-12-12 20:55 UTC, TysonRayJones commented on src/Propagation/generics.jl
> +Propagate a Pauli sum  through the circuit `circ` in the Heisenberg picture.
same as last comment (clarifying Heisenberg prop means circ is daggered, and explaining thetas)

2024-12-12 20:56 UTC, TysonRayJones commented on src/Propagation/generics.jl
> +3nd-level function below `applymergetruncate!` that applies one gate to one Pauli string in `psum`, moving results into `output_psum` in the process.
"3nd-level" should be "3rd-level" (hehe)

2024-12-12 20:57 UTC, TysonRayJones commented on src/Propagation/generics.jl
> +    # If we want to reduce unnecessary Pauli string movement, we can overload applygatetoall!()
"applygatetoall" in comment should be updated to "applytoall" as per rename

2024-12-12 20:58 UTC, TysonRayJones commented on src/Propagation/specializations.jl
> +@inline function applyandadd!(gate::CliffordGate, pstr, coeff, theta, aux_psum, args...; kwargs...)
not so important, but `aux_psum` here should be called `output_psum`

2024-12-13 10:18 UTC, MSRudolph commented on src/PauliAlgebra/datatypes.jl
> +function +(pstr1::PauliString{TermType,CoeffType}, pstr2::PauliString{TermType,CoeffType}) where {TermType,CoeffType}
Done ef0485740a445831158ee8bcc48ed68e2d07a4aa

2024-12-13 10:21 UTC, MSRudolph commented on src/PauliAlgebra/datatypes.jl
> +The type of the Pauli string needs to be the keytype of the dictionary, and the coefficient `coeff` needs to be the keytype.
Done 8a0b7716f131dd36f5752812b293d75772b3b971

2024-12-13 10:21 UTC, MSRudolph commented on src/PauliAlgebra/datatypes.jl
> +The type of the Pauli string needs to be the keytype of the dictionary, and the coefficient `coeff` needs to be the keytype.
8a0b7716f131dd36f5752812b293d75772b3b971

2024-12-13 10:21 UTC, MSRudolph commented on src/PauliAlgebra/datatypes.jl
> +The type of the Pauli string needs to be the keytype of the dictionary, and the coefficient `coeff` needs to be the keytype.
8a0b7716f131dd36f5752812b293d75772b3b971

2024-12-13 12:02 UTC, MSRudolph commented on src/Propagation/generics.jl
> +3nd-level function below `applymergetruncate!` that applies one gate to one Pauli string in `psum`, moving results into `output_psum` in the process.
60c60c9b0d24654f4406497eb265dce22ee901b9

2024-12-13 12:02 UTC, MSRudolph commented on src/Propagation/generics.jl
> +Propagate a Pauli sum  through the circuit `circ` in the Heisenberg picture.
60c60c9b0d24654f4406497eb265dce22ee901b9

2024-12-13 12:02 UTC, MSRudolph commented on src/Propagation/generics.jl
>  Propagate a `PauliSum` through the circuit `circ` in the Heisenberg picture.
60c60c9b0d24654f4406497eb265dce22ee901b9

2024-12-13 12:02 UTC, MSRudolph commented on src/PauliAlgebra/datatypes.jl
> +Empty the `PauliSum` by emtpying the dictionary on the `terms` fields.
60c60c9b0d24654f4406497eb265dce22ee901b9

2024-12-13 12:02 UTC, MSRudolph commented on src/PauliAlgebra/datatypes.jl
> +    # delete if the coefficient would be set to 0
60c60c9b0d24654f4406497eb265dce22ee901b9

2024-12-13 12:02 UTC, MSRudolph commented on src/Propagation/generics.jl
> +    # If we want to reduce unnecessary Pauli string movement, we can overload applygatetoall!()
60c60c9b0d24654f4406497eb265dce22ee901b9

2024-12-13 12:02 UTC, MSRudolph commented on src/Propagation/specializations.jl
> +@inline function applyandadd!(gate::CliffordGate, pstr, coeff, theta, aux_psum, args...; kwargs...)
60c60c9b0d24654f4406497eb265dce22ee901b9

2024-12-13 13:10 UTC, merged